apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: HelloNodeDeploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: HelloNode
    spec:
      containers:
      - name: HelloNode
        image: 1986895/myimage:latest
        ports:
        - containerPort: 80
