apiVersion: apps/v1
kind: Deployment
metadata:
  name: HelloNodeDeploy
  labels:
    app: HelloNode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HelloNode
  template:
    metadata:
      labels:
        app: HelloNode 
    spec:
      containers:
      - name: HelloNode
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        
