apiVersion: v1
kind: Service
metadata:
  name: HelloNodeService
spec:
  selector:
    app: HelloNode 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110


